[workspace]
members = [
  "crates/chameleon-core",
  "crates/chameleon-client",
  "crates/chameleon-bridge"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2026"
license = "GPL-3.0-or-later"
